apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: movie-app
type: Opaque
stringData:
  MONGO_URI: "mongodb://admin:password@mongodb:27017/my-mongodb?authSource=admin"
  MONGO_DB: "my-mongodb"
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "password"
